feat: sticky header for table
zenkigen/zenkigen-component pull request #319
Opened 2024-07-01 07:29 UTC by Orust

### 概要
テーブルコンポーネントにスクロール時にヘッダーを上部に固定する機能を追加。これにより、ユーザがテーブルをスクロールしてもヘッダーが常に表示されるようになる。

### 変更内容
1. **TableCell コンポーネントの修正**:
   - `isHeader` プロパティを追加し、ヘッダーセルとして識別できるようにした。
   - ヘッダーセルにスクロール時に固定するスタイルを追加。

2. **TableStoryBasic コンポーネントの修正**:
   - ヘッダーセルに `isHeader` プロパティを追加し、スクロール時に固定されるようにした。

2024-07-03 07:13 UTC, yutakam80 requested changes
@Orust

2024-07-03 07:13 UTC, yutakam80 commented on packages/component-ui/src/table/table.stories.tsx
> +  const handleSortName = useCallback((direction: SortOrder) => {
命名規則は handle（イベント名）XXX というルールにしているのでそれに則ってください。

2024-07-03 07:13 UTC, yutakam80 commented on packages/component-ui/src/table/table-cell.tsx
> +      className={clsx('border-b border-uiBorder01', isHeader === true ? 'sticky top-0 z-10 bg-white' : '', className)}
clsx の機能でクラスの付け外しができるのでこちらの機能を使ってください。
https://github.com/lukeed/clsx?tab=readme-ov-file#usage

また、このような処理を JSX 内に記述すると可読性が悪くなるため class 用の変数を作って前処理してください。

2024-07-03 10:39 UTC, Orust commented on packages/component-ui/src/table/table-cell.tsx
> +  isHeader?: boolean | null;
消し忘れていました、不要なので削除しました！

2024-07-03 10:39 UTC, Orust commented on packages/component-ui/src/table/table.stories.tsx
> +  const handleSortName = useCallback((direction: SortOrder) => {
`handleClickSortName`のように既存コードと共に書き換えました

2024-07-03 10:41 UTC, Orust commented on packages/component-ui/src/table/table-cell.tsx
> +      className={clsx('border-b border-uiBorder01', isHeader === true ? 'sticky top-0 z-10 bg-white' : '', className)}
他の実装箇所も参考にして、クラスの付け外し、classの前処理をするように修正しました！

2024-07-03 13:57 UTC, yutakam80 requested changes
@Orust

2024-07-03 13:57 UTC, yutakam80 commented on packages/component-ui/src/table/table.stories.tsx
> +  const handleClickSortName = useCallback((direction: SortOrder) => {
handle しているイベント名は onClick じゃなくて onChange ですよね？
なので handleChangeXXX にしてください。

2024-07-03 13:57 UTC, yutakam80 commented on packages/component-ui/src/table/table-cell.tsx
> +  const classes = clsx('border-b border-uiBorder01', { 'sticky top-0 z-10 bg-white': isHeader ?? false }, className);
ちょっと細かいですが、この場合はデフォルト引数で false を指定したほうがいいと思います
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions/Default_parameters

2024-07-04 05:21 UTC, Orust commented on packages/component-ui/src/table/table-cell.tsx
> +  const classes = clsx('border-b border-uiBorder01', { 'sticky top-0 z-10 bg-white': isHeader ?? false }, className);
参考リンクもありがとうございます！条件分岐を減らせて、書き方も簡潔にできました

2024-07-04 05:21 UTC, Orust commented on packages/component-ui/src/table/table.stories.tsx
> +  const handleClickSortName = useCallback((direction: SortOrder) => {
度々すみません、こちらも修正しました

2024-07-04 05:23 UTC, yutakam80 approved these changes

2024-07-04 05:47 UTC, merged